"""empty message

Revision ID: 43d12cb2c03d
Revises: 
Create Date: 2025-05-09 23:15:38.697471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d12cb2c03d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accomodation',
    sa.Column('accomodation_id', sa.Integer(), nullable=False),
    sa.Column('accomodation_type', sa.String(length=50), nullable=False),
    sa.Column('accomodation_name', sa.String(length=50), nullable=True),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('accomodation_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('wallet', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('travel',
    sa.Column('travel_id', sa.Integer(), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=True),
    sa.Column('have_organized', sa.Boolean(), nullable=True),
    sa.Column('have_guide', sa.Boolean(), nullable=True),
    sa.Column('is_desp', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('accomodation_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.String(length=10), nullable=False),
    sa.Column('created_time', sa.String(length=5), nullable=False),
    sa.Column('last_updated_date', sa.String(length=10), nullable=False),
    sa.Column('last_updated_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['accomodation_id'], ['accomodation.accomodation_id'], ),
    sa.PrimaryKeyConstraint('travel_id')
    )
    op.create_table('favorite',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.String(length=10), nullable=False),
    sa.Column('added_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['travel_id'], ['travel.travel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['travel_id'], ['travel.travel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('price_for_one', sa.Float(), nullable=False),
    sa.Column('transportation_organization', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('date_comback', sa.String(length=10), nullable=False),
    sa.Column('time_comback', sa.String(length=5), nullable=False),
    sa.Column('starting_place', sa.String(length=150), nullable=False),
    sa.Column('destination_place', sa.String(length=150), nullable=False),
    sa.Column('travel_method', sa.String(length=100), nullable=False),
    sa.Column('starting_place_comeback', sa.String(length=150), nullable=False),
    sa.Column('destination_place_comeback', sa.String(length=150), nullable=False),
    sa.Column('have_stopover', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travel.travel_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_organized', sa.Boolean(), nullable=True),
    sa.Column('with_guide', sa.Boolean(), nullable=True),
    sa.Column('added_date', sa.String(length=10), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.ForeignKeyConstraint(['travel_id'], ['travel.travel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('order')
    op.drop_table('ticket')
    op.drop_table('review')
    op.drop_table('favorite')
    op.drop_table('travel')
    op.drop_table('user')
    op.drop_table('accomodation')
    # ### end Alembic commands ###
