"""empty message

Revision ID: 88341821b4a6
Revises: 43d12cb2c03d
Create Date: 2025-05-12 11:53:24.276323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88341821b4a6'
down_revision = '43d12cb2c03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
